---
- hosts: ${target}
  user: root
 
  tasks:
  - include: common.yml

  - name: Run ganeti-backup export script
    action: command /usr/bin/nice -n 20 /usr/bin/ionice -c 2 -n 7 /tmp/ganeti-backup/ganeti-backup.py export
